### ISSUE TITLE
Git strategy for multiple developers

### ISSUE THREAD

**Issue by aesopwolf** [fedor/node-no-config#2]
I like the idea behind this setup and would love to use it, but it's lacking in one area...

Currently, each developer on my team has their own custom `config/development.js` file which is kept out of version control. Obviously this project won't be able to handle this.

So, do you have a suggested strategy for dealing with this scenario? I feel like it's not an edge case, in which a majority of other teams do this as well.

What are your thoughts on still maintaining a `config-development.js` file and just performing a deep merge with the main `config.js` file?

**Comment by fedor** [comment]
Hi @aesopwolf, a way to handle it **in the code level** is to merge them (e.g. with default [Object.assign](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)):

``` js
require('no-config')({
    config: Object.assign(
        {},
        require('./config/config.js'),
        require('./config/development.js')
    )
}).then(
    ...
)
```

`config/development.js` in the repo can be:

``` js
module.exports = {}
```

But for some developer:

``` js
module.exports = {
    redis: {
        development: {
            host: 'joe.sample.com'
        }
    }
}
```

If you have a lot of config environments (`production`, `testing`, `uat`, `qa`, etc.) it still worth to split it to config.js + development.js first (just for one environment). However, in general, this approach replicates the notion from `config` module: to keep different environments in different files. Which decrease config maintainability.

`a majority of other teams do this as well`. Well, I'm not sure about a majority, but, a lot of teams **require** developers to have identical local environments for the same project, e.g. unified host name, ports, db names, etc. This seems like the best approach to me.
