### ISSUE TITLE
Not working with mongoose... ?

### ISSUE THREAD

**Issue by tomasgvivo** [fedor/node-no-config#3]
So I have the following code:
===

```
process.env.NODE_ENV = 'prod';

const config = {
  mongoose: {
    init: (params) => mongoose.createConnection(params.uri, params.options, params.config, params.config.autoIndex, true),
    default: {
      uri: 'mongodb://localhost/test-db',
    },
    dev: {
      uri: 'mongodb://localhost/test-db-dev',
    },
    prod: {
      uri: 'mongodb://localhost/test-db-prod',
    }
  }
}

const mongoose = require('mongoose')
const co = require('co')
co(function* () {
    let conf = yield require('no-config')({config})
 
    console.log('ENV', conf.env)
    // > prod
    console.log('Mongoose:', conf.mongoose.uri)
    // > Mongoose: mongodb://localhost/test-db-prod
    console.log(conf.mongoose.instance)
    // > undefined
})
```
I understand that ```conf.mongoose.instance``` should be the resolved promise of ```mongoose.createConnection``` instead of ```undefined```.

Further test:
===
If I modify the init like this...
```
{
  mongoose: {
    init: (params) => {
      console.log('test');
      return mongoose.createConnection(params.uri, params.options, params.config, params.config.autoIndex, true)
    }
  }
}
```
...```"test"``` will never be logged.

Any idea of what i'm doing wrong?

**Comment by fedor** [comment]
@tomasgvivo what node.js and mongoose versions you've tried to use?
Do you override native Promise implementation?
If yes, what implementation do you use? 
I've tried with `Promise.resolve()` and it works.
Also, you may try to put `try { ... } catch { ... }` inside init() + debug print iniside `catch` block
